### ISSUE TITLE
/how_tos/threading_and_queues/index.md 번역해보겠습니다.

### ISSUE THREAD

**Issue by corona10** [tensorflowkorea/tensorflow-kr#117]

**Comment by corona10** [comment]
개인적인 사정으로 진행하기가 어려워 다른분에게 부탁드려야 할것 같습니다.
시간이 많이 지났지만 #149 분이 이어서 하셔도 될것 같습니다.

**Comment by seoz** [comment]
기대중인데, 아쉽네요. 다음에 부탁드려요 ^^

**Comment by corona10** [comment]
@seoz 
서주영님께서 보고 계시다니 부끄럽네여 ㅎㅎ 
이것저것 일이 밀려 치일피일 미루어지다가 다른분들이 진행할수 있는데,
제가 붙잡고 있는 것 같아 일단 이슈를 닫았습니다. 방학이나 좀더 여유있을 때에 기여해보도록 하겠습니다.
