### ISSUE TITLE
텐서플로우 10월 번역 이벤트 안내

### ISSUE THREAD

**Issue by rickiepark** [tensorflowkorea/tensorflow-kr#196]
번역에 참여해 주신 모든 분들께 감사드립니다.
페이스북 텐서플로우 그룹에서 10월 한달간 번역에 참여해 주신 분들을 대상으로 텐서플로우 티셔츠를 제공하는 이벤트를 열었습니다.(아래 링크 참조)
https://www.facebook.com/groups/TensorFlowKR/permalink/356194588054939/?match=c3VuZyBraW0%3D

이 이벤트에 해당되시는 분들의 깃허브 아이디입니다.
jybaek, intelcoder, lsrock1, mingrammer, datalater, recisic, johnchoi83, iworkist, sgwassabi, DSKSD

티셔츠는 XL 2개, L 3개, M 5개가 있습니다.
주문 하시는 대로 선착순으로 배송될 것 같습니다. ^^
신청하시는 방법은 이 이슈에 코멘트로 페이스북 아이디를 알려 주세요.
그리고 페이스북에서 메세지로 저에게 주소와 성함, 연락처를 보내 주시면 우편으로 배송하고 회신 드리겠습니다.
아니면 페이스북의 포스트에 댓글로 알려 주셔도 좋습니다.
https://www.facebook.com/groups/TensorFlowKR/permalink/380359258971805/

감사합니다.

**Comment by jybaek** [comment]
페이스북 : oops.jybaek@gmail.com // JaeYeon Baek
감사합니다. 더 꾸준한 기여를 할 수 있도록 노력하겠습니다.

**Comment by DSKSD** [comment]
tjdehd1222@naver.com  (김성동)

감사합니다..!!

**Comment by mingrammer** [comment]
k239507@gmail.com Ming Kwon (권민재)

감사합니다 ^^

**Comment by lsrock1** [comment]
lsrock1@naver.com 이상록
감사합니다!

**Comment by datalater** [comment]
the7mincheol@gmail.com
www.facebook.com/novahora
조민철

감사합니다!!

**Comment by iworkist** [comment]
jaehong747
박재홍

감사합니다! ^^

**Comment by recisic** [comment]
recisic@gmail.com 남준오
감사합니다!

**Comment by rickiepark** [comment]
@intelcoder, @johnchoi83, @sgwassabi 님 안녕하세요. 
텐서플로우 번역 이벤트에 당첨 되셨습니다. 
페이스북으로 티셔츠 주문 부탁드립니다. 지금 XL 사이즈 하나, M 사이즈 두개가 남았습니다.
혹 페이스북 텐서플로우 그룹 회원이 아니시면 이슈의 댓글로 알려 주셔도 됩니다.

**Comment by sgwassabi** [comment]
sgwassabi
SeungGap Choi (최승갑)
감사합니다!!

**Comment by johnchoi83** [comment]
johnchoi83@gmail.com, 최종우
감사합니다.

**Comment by intelcoder** [comment]
감사합니다 ! 
페이스북 아이디는 메세지로 보내드리면 안될까요 ? 
이름: 김성준
