### ISSUE TITLE
/g3doc/how_tos/reading_data/index.md 번역 시작해보겠습니다. (+질문있습니다)

### ISSUE THREAD

**Issue by faithon** [tensorflowkorea/tensorflow-kr#214]
제가 처음 번역작업을 시작해보는건데, 미흡해도 괜찮을런지요..?

**Comment by rickiepark** [comment]
네 괜찮습니다. 우리 모두 미흡해요! :-)

**Comment by faithon** [comment]
번역작업을 몇줄 못해놓아서 올릴 면목이 없네요. 혹시 다른분중에서 번역하시고자 하시면 해주세요.
사정이 나아져서 다시 할 수 있게되면 글 남기기겠습니다. ^^;;

**Comment by rickiepark** [comment]
괜찮습니다. ^^ 
이 이슈는 그럼 종결하겠습니다. 👍
