### ISSUE TITLE
r1.0 내용에 대한 원문 업데이트가 필요할 듯 합니다

### ISSUE THREAD

**Issue by mikigom** [tensorflowkorea/tensorflow-kr#216]
정식 버전인 r1.0도 등장했으니 r1.0에 대한 원문 업데이트가 필요할 듯 합니다.

**Comment by rickiepark** [comment]
넵 업데이트 하도록 하겠습니다. 👍

**Comment by rickiepark** [comment]
업데이트가 늦어져서 죄송합니다. r1.0 브랜치에 1.0 버전 문서를 올렸습니다. :-)
