### ISSUE TITLE
git book에서 tf.contrib.learn 관련 튜토리얼 문서 링크 접근 문제

### ISSUE THREAD

**Issue by mikigom** [tensorflowkorea/tensorflow-kr#25]
tutorials/index.md 문서 번역 작업을 하다가 git book에서 tf.contrib.learn의 튜토리얼 관련된 문서에 접근할 수 없는 것을 확인하였습니다. 구체적으로는 다음과 같습니다.

tutorials/tflearn/index.md
tutorials/linear/overview.md
tutorials/wide/index.md
tutorials/wide_and_deep/index.md

**Comment by rickiepark** [comment]
네 0.9 버전에서 새로이 추가되거나 위치가 변경된 페이지들이 있습니다.
깃북의 링크를 제가 찾아서 수정하겠습니다.

**Comment by mikigom** [comment]
감사합니다. :)

**Comment by rickiepark** [comment]
별말씀을요 ; )

**Comment by rickiepark** [comment]
페이지 링크 수정했습니다.

tensorflow.org 의 튜토리얼 링크와 실제 페이지의 제목이 좀 안어울리는 면이 있습니다.
예를 들어 'Overview of Linear Models with tf.contrib.learn' 는 linear/overview.md 로 링크가 되는데요.
이 페이지의 타이틀은 'Large-scale Linear Models with TensorFlow' 로 되어 있는 식입니다.

깃북이 좌측 메뉴는 SUMMARY.md 를 수정하면 되는데 tensorflow.org 의 링크 이름을 기준으로 수정했습니다.
즉 linear/overview.md 파일의 제목 'Large-scale Linear Models with TensorFlow' 을 기준으로 하지 않고
'Overview of Linear Models with tf.contrib.learn' 를 이용하여 linear/overview.md 에 링크를 걸었습니다.

`[tf.contrib.learn 선형모델 소개](g3doc/tutorials/linear/overview.md)`

물론 SUMMARY.md 파일을 다시 수정하셔도 괜찮습니다. ^^

**Comment by mikigom** [comment]
SUMMARY.md에서 신택스넷을 SyntaxNet으로 일치시키는 것을 제외하고는, 모두 tutorials/index.md를 수정하는 방향으로 일치시켰습니다. 아무래도 비교적 최근에 나온 프레임워크의 명칭은 영어로 남겨두는 게 좋다고 생각했습니다.

**Comment by rickiepark** [comment]
넵 좋습니다. :-)
