### ISSUE TITLE
github markdown에서 equation rendering 문제

### ISSUE THREAD

**Issue by mikigom** [tensorflowkorea/tensorflow-kr#30]
Rendering math equations? https://github.com/github/markup/issues/274

현재 github markdown 내에서 latex와 MathJax을 기반으로 두고 있는 rendering을 지원하지 않는다는 사실을 처음 알았습니다. 예를 들어 제가 지금 작업하고 있는 /tutorials/mnist/beginners/index.md 경우에는 적지 않은 수식이 등장합니다. 북 전체적으로 봤을 때도 적지 않은 수식이 등장하리라 예상합니다.

**Comment by rickiepark** [comment]
네 제가 확인해 보고 다시 코멘트 드리겠습니다.

**Comment by rickiepark** [comment]
gitbook에서 수식이 표현되게 하기 위해 book.json 파일을 추가했습니다.
https://tensorflowkorea.gitbooks.io/tensorflow-kr/content/g3doc/tutorials/mnist/beginners/
확인 부탁 드립니다.

**Comment by mikigom** [comment]
확인하였습니다. 감사합니다.
