### ISSUE TITLE
g3doc/how_tos/index.md 시작합니다

### ISSUE THREAD

**Issue by totuta** [tensorflowkorea/tensorflow-kr#5]
일단 시작하겠습니다.

제안 : index 등은 @tensorflowkorea 님께서 일괄적으로 하시는 것이 어떨까 합니다만,
(용어나 개념등의 기준을 잡기 위해서)
어떻게 생각하시는지요?

**Comment by rickiepark** [comment]
네 보통 용어나 번역의 규칙등을 정해서 시작하기도 합니다만 저는 조금 생각이 다릅니다.
사람마다 TensorFlow를 '텐서플로우', '텐서플로' 혹은 있는 그대로 영어로 쓰자고 할 수 있는데요.
사실 세가지다 모두 틀린 것은 아니라서 굳이 셋중에 하나를 정할 필요가 있을까 생각이 듭니다.
이게 머 멋있게 단장을 해야하는 일이 아니고 필요한 사람들에게 정보를 주고자 하는 취지인데요.
여러 사람이 나누어 하다보면 달라지는 게 자연스러운거고 서로간에 번역의 질도 차이가 날 수 있습니다.
다소 어수선하더라도 있는 각자의 생각 있는 그대로를 배려하는 게 어떨까 합니다.
그리고 필요하다면 작업이 완료된 후 한 두분이 전체를 정리하실 수 있을 것 같습니다.
규칙은 그 때 정해도 늦지 않을 것 같습니다. 다른 의견도 언제든지 환영입니다. ^^

함께 도와주셔서 다시한번 감사드립니다. 즐거운 주말 되세요 :-)

**Comment by totuta** [comment]
잘 알겠습니다. 그것도 좋은 방법인것 같네요.

열심히 차곡차곡 하도록 하겠습니다.

**Comment by totuta** [comment]
1차 완료하였습니다.
