### ISSUE TITLE
tutorial word2vec 해보겠습니다.

### ISSUE THREAD

**Issue by hunkim** [tensorflowkorea/tensorflow-kr#61]

**Comment by hunkim** [comment]
보니 재미있네요. 한번 해보겠습니다.

**Comment by rickiepark** [comment]
교수님, https://github.com/tensorflowkorea/tensorflow-kr/invitations 링크로 들어오시면 콜라보레이터로 등록되세요. 그럼 직접 머지하실 수도 있습니다.
