### ISSUE TITLE
g3doc/tutorials/deep_cnn/index.md 시작해보겠습니다

### ISSUE THREAD

**Issue by easyaction** [tensorflowkorea/tensorflow-kr#65]

**Comment by hunkim** [comment]
Deep CNN 기대 됩니다. 감사합니다.

**Comment by johnchoi83** [comment]
저도 번역 참여하고 싶은데 가능할까요? 12일 전에 시작하시고 아직 0%라 진행하고 싶습니다. 이후 다른 tutorial 도 진행하려고 합니다.

**Comment by easyaction** [comment]
@johnchoi83 죄송합니다 100% 를 한번에 풀리퀘 하려고 해서 아직 반영을 못했습니다
이번 주 주말까지는 마무리하려고 하는데 그때까지만 기다려주실 수 있을까요?

**Comment by johnchoi83** [comment]
아 죄송합니다. 진행하시는 것이면 다른 것을 찾아보도록 하겠습니다. 답변 감사합니다.
